name: Generate Datas

on:
  schedule: # execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar Dados
    runs-on: ubuntu-latest
    steps:
      # Animação de Cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Bianca-Ribeiro-0
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Criar Arquivo de Ambiente
        id: create_env_file
        run: echo "GITHUB_SVG_PATH=dist/github-contribution-grid-snake.svg" >> ${{ github.workspace }}/.env

      - name: GitHub Pages
        id: gh_pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
